[supervisord]
nodaemon=true

[program:xvfb]
command=Xvfb :1 -screen 0 800x700x16
autorestart=true
priority=1

[program:fluxbox]
command=fluxbox
environment=DISPLAY=":1"
autorestart=true
priority=2

[program:tictactoe]
command=python main.py
directory=/app
environment=DISPLAY=":1"
autorestart=true
priority=3

[program:x11vnc]
command=x11vnc -display :1 -forever -shared -nopw -rfbport 5900
autorestart=true
priority=4

[program:novnc]
command=websockify --web=/usr/share/novnc 6080 localhost:5900
autorestart=true
priority=5
